FROM webdevops/nginx:alpine

LABEL description="Serving compiled front-end website using the latest nodeJS and Nginx"
# ------------------------------------------------------------------------
# Install latest version of nodejs + npm
# ------------------------------------------------------------------------
RUN apk add --update npm
